### ISSUE TITLE
Server doesn't accept new writes after truncate table

### ISSUE THREAD

**Issue by mtrencseni** [scalien/scaliendb#100]
To reproduce:

Have a quorum with 2 nodes.
Have the client write into it.
Kill one of the nodes.
The client will keep going (OK).
Now issue a truncate table.
The client will stop writing. Restarting the client doesn't help.
The shard server is stuck. You have to restart the shard server.

**Comment by mtrencseni** [comment]
It seems that replication gets stuck (IsAppending() is true).

**Comment by scalien** [comment]
Can't reproduce in storage-track branch.
