### ISSUE TITLE
Fix make script that it can build javalib on Linux

### ISSUE THREAD

**Issue by burinov** [scalien/scaliendb#141]
At the moment make cannot build javalib on Linux because of mac-specific paths to java headers (jni.h).

<pre>
max@ubuntu:~/scaliendb$ make javalib
mkdir -p ./build/mkrelease \
                ./bin \

g++ -Wall -W -fPIC -I./src  -DPLATFORM_LINUX -D__STDC_FORMAT_MACROS -D_FILE_OFFSET_BITS=64 -O2  -I/System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Headers/ -I/System/Library/Frameworks/JavaVM.framework/Versions/1.5.0/Headers/ -I/Developer/SDKs/MacOSX10.6.sdk/System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Headers/ -I/Developer/SDKs/MacOSX10.5.sdk/System/Library/Frameworks/JavaVM.framework/Versions/1.6.0/Headers/ -I/Developer/SDKs/MacOSX10.5.sdk/System/Library/Frameworks/JavaVM.framework/Versions/1.5.0/Headers/ -I/usr/java/jdk/include/ -I/usr/lib/jvm/java-6-sun/include/ -I/usr/lib/jvm/java-6-sun/include/linux -o build/mkrelease/Application/Client/Java/scaliendb_client_java.o -c ./src/Application/Client/Java/scaliendb_client_java.cpp
./src/Application/Client/Java/scaliendb_client_java.cpp:138: fatal error: jni.h: No such file or directory
compilation terminated.
make: *** [build/mkrelease/Application/Client/Java/scaliendb_client_java.o] Error 1
max@ubuntu:~/scaliendb$
</pre>

**Comment by agazso** [comment]
Hello,

In order to build Java client library on Ubuntu, first you have to
install the openjdk-6-jdk package with this command:

$ sudo apt-get install openjdk-6-jdk

Let me know if it works.

Attila

On Wed, Jun 29, 2011 at 14:51, burinov
reply@reply.github.com
wrote:
