### ISSUE TITLE
CRC checks on disk

### ISSUE THREAD

**Issue by mtrencseni** [scalien/scaliendb#15]

**Comment by tav** [comment]
Perhaps consider Mrumur2 for this and the network check? It performs slightly better and gives added redundancy on the filesystem checks which often use CRC. Here's a comparison to CRC on http://www.strchr.com/hash_functions

And here's the C++ implementation: http://sites.google.com/site/murmurhash/

**Comment by mtrencseni** [comment]
Thanks, will look into it.
