### ISSUE TITLE
Make errors on FreeBSD 9.0

### ISSUE THREAD

**Issue by ghost** [scalien/scaliendb#156]
When running "make" in the scaliendb folder under FreeBSD 9.0 Current, the following errors are observed:

> "Makefile", line 42: Missing dependency operator
> "Makefile", line 44: Need an operator
> "Makefile", line 45: Missing dependency operator
> "Makefile", line 47: Need an operator
> "Makefile", line 48: Missing dependency operator
> "Makefile", line 50: Need an operator
> "Makefile", line 52: Need an operator
> "Makefile", line 53: Need an operator
> "Makefile", line 54: Need an operator
> "Makefile", line 57: Need an operator
> "Makefile", line 60: Need an operator
> "Makefile", line 84: Missing dependency operator
> "Makefile", line 89: Need an operator
> "Makefile", line 94: Need an operator
> "Makefile", line 139: warning: duplicate script for target "./build/mkrelease/%.o" ignored
> make: fatal errors encountered -- cannot continue

Note that it is trying to use the "Makefile.Darwin" script.

Running this file with the "gmake" command gets me further, but it soon exits with the following error:

> gmake targets BUILD="release"
> gmake[1]: Entering directory `/root/scaliendb'
> g++ -Wall -W -I./src -DPLATFORM_DARWIN -D__STDC_FORMAT_MACROS -O2  -o build/mkrelease/Application/Client/SDBPClientRequest.o -c src/Application/Client/SDBPClientRequest.cpp
> In file included from ./src/System/Common.h:7,
>                  from ./src/System/Containers/List.h:6,
>                  from src/Application/Client/SDBPClientRequest.h:4,
>                  from src/Application/Client/SDBPClientRequest.cpp:1:
> ./src/System/Platform.h:79:20: error: alloca.h: No such file or directory
> gmake[1]: *** [build/mkrelease/Application/Client/SDBPClientRequest.o] Error 1
> gmake[1]: Leaving directory`/root/scaliendb'
> gmake: **\* [release] Error 2

**Comment by agazso** [comment]
You have to use gmake in order build ScalienDB on FreeBSD. Also I changed alloca.h to a more standard conforming stdlib.h, so it should build now.
