### ISSUE TITLE
ClusterID may stuck in 0, therefore rejecting other nodes from connecting

### ISSUE THREAD

**Issue by agazso** [scalien/scaliendb#180]
If a node already has a nodeID, but its clusterID somehow stucks in 0, it may connect to other nodes, but other nodes trying to connect to it will be rejected because of clusterID mismatch.

The check for clusterID happens in ClusterConnection::OnMessage, but it is checked only in case when the clusterID is non-zero.

**Comment by mtrencseni** [comment]
Fixed.
