### ISSUE TITLE
Client missing port

### ISSUE THREAD

**Issue by mtrencseni** [scalien/scaliendb#187]
Felélesztettem a tegnapi clustert, és próbáltam újra mérni, de ezt a
hibaüzenetet kaptam:

/home/ubuntu/scaliendb/bin/java/libscaliendb_client.so(_ZN9Countdown8SetDelayEm+0x23)[0x7fbeff9df0b3]
/home/ubuntu/scaliendb/bin/java/libscaliendb_client.so(_ZN13TCPConnection7ConnectER8Endpointj+0x12f)[0x7fbeff9d9d8f]
/home/ubuntu/scaliendb/bin/java/libscaliendb_client.so(_ZN10SDBPClient20ControllerConnectionC1EPNS_6ClientEmR8Endpoint+0x116)[0x7fbeff9cb996]
/home/ubuntu/scaliendb/bin/java/libscaliendb_client.so(_ZN10SDBPClient6Client4InitEiPPKc+0x152)[0x7fbeff9c3332]
[0x7fbf060edcc8]
java: src/System/Events/Countdown.cpp:11: void
Countdown::SetDelay(uint64_t): Assertion `next == prev && next ==
this' failed.
## 

Mint kiderült, nem a ScalienDB-ben volt a hiba, hanem csak
elfelejtettem kiírni a portszámot :)

**Comment by agazso** [comment]
Fixed, throws SDBP_API_ERROR.
