### ISSUE TITLE
~ShardQuorumProcessor() destructor ASSERT on CTRL+C

### ISSUE THREAD

**Issue by mtrencseni** [scalien/scaliendb#254]
Occured on 64-bit Windows Debug mode, running 1 controller 2 shard server, hitting CTRL+C on the shard servers in the console window:

  ShardQuorumProcessor::~ShardQuorumProcessor()
  {
      Shutdown();
  }

It's not clear based on the call stack whether Shutdown() actually ran. The IP was on the closing brace, but the top of the call stack after ~ShardQuorumProcessor() was kernel code, as if it's already deallocating memory on its part.

The ShardQuorumProcessor itself looked fine, as you would expect before deallocation. It was running in Debug mode and there were no "fefe" pointers.

**Comment by scalien** [comment]
See #301
