### ISSUE TITLE
Client close problem

### ISSUE THREAD

**Issue by szabozs** [scalien/scaliendb#297]
Client destroy (Finalize) without client.Close called causes Access violation.

**Comment by szabozs** [comment]
Reproducing:

The SimpleUnitTests.CreateAndCloseClients test reproduces the issue, but only if there is another active test, CountBeforeSubmit for example. Adding either of following lines to the end of CreateAndCloseClients solves the problem.

client1.Submit();
client1.Close();

**Comment by szabozs** [comment]
---

## Microsoft Visual C++ Runtime Library

Assertion failed!

Program: ...
File: ..\src\Application\Client\SDBPClient.cpp
Line: 1263

Expression: table != 0

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts

## (Press Retry to debug the application - JIT must be enabled)

## Abort   Retry   Ignore

**Comment by szabozs** [comment]
The assert is normal if garbage collector calls the destructor and there are unsent requests, while another thread already deleted the database or table.

**Comment by scalien** [comment]
Fixed in https://github.com/scalien/scaliendb/commit/9fc30a4d8d1a77d373d6fe3532625bde5a735739
