### ISSUE TITLE
Http API not complete

### ISSUE THREAD

**Issue by bromokun** [scalien/scaliendb#298]
Dear sir,

I try to develop client lib using Erlang, and I really want to use ScalienDB through its HTTP API.
I believe that your HTTP API doesn't complete yet, because I'm looking for an API to select Database by name and couldn't find it.
I check the Java API, and everything are there, from: connecting to Shard, selecting database, selecting table then do CRUD operations.
Do you guys are planning to add more HTTP API?

**Comment by mtrencseni** [comment]
Hi,

Use getState on HTTP, then extract databaseID/tableID from the JSON.
Our regular client APIs (Java/C#/Python) don't use HTTP, they use SWIG to
generate wrappers and use the ScalienDB protocol.
If you use HTTP, it'll be somewhat slower.

Best:

-- Marton Trencseni

**Comment by bromokun** [comment]
Thank you very - very much mtrencseni ...
