### ISSUE TITLE
mistyped example in HTTP API documentation

### ISSUE THREAD

**Issue by ghost** [scalien/scaliendb#358]
I found a mistyped example on page https://github.com/scalien/scaliendb/wiki/HTTP-API-Documentation .
If you look at the rename quorum example request, as you can see:
http://localhost:8080/createQuorum?quorumID=1&name=quorum123 ,
which is wrong. The correct is :
http://localhost:8080/renameQuorum?quorumID=1&name=quorum123

**Comment by agazso** [comment]
Fixed
