### ISSUE TITLE
JSON error in getState

### ISSUE THREAD

**Issue by ghost** [scalien/scaliendb#359]
I started to use the scaliendb with the provided single-controller-configuration (what is in the test folder). Maybe it's not important, but I found a little bug.

After I start the single controller, I'm tried to use the HTTP API form Javascript.  You can also reproduce this if you simply use wget or curl or enter it directly to the  address bar of any browser.

First I try to call http://localhost:8080/getState . Ok, everything seems to be fine, but the main object literal is not closed (missing } on the end)!  After that, I went to the web console and start debug how it handled? The web console is not calling the same URL , what can be seen in the documentation. It uses  http://localhost:8080/json/getState and if you use that, this bug is not present...

Maybe modify the documentation to the right request url or fix the ending of the output JSON, please.

**Comment by agazso** [comment]
Fixed the docs.
