### ISSUE TITLE
BUG when returned null value with java client

### ISSUE THREAD

**Issue by rwxybh** [scalien/scaliendb#360]
maybe fixed by changing Client.java:

for example:

static String byteArrayToString(byte[] b) throws SDBPException {
        try {
            return (b == null) ? null : new String(b, "UTF8"); // corrent
                        return new String(b, "UTF8"); // wrong
        } catch (Exception e) {
            throw new SDBPException(Status.SDBP_API_ERROR,
                    "Cannot convert byte[] to String using UTF-8");
        }
    }

**Comment by mtrencseni** [comment]
Can you describe the problem in more detail?

**Comment by rwxybh** [comment]
look at the following code fragment in Client.java

static String byteArrayToString(byte[] b) throws SDBPException {
try {
return new String(b, "UTF8"); 
} catch (Exception e) {
throw new SDBPException(Status.SDBP_API_ERROR,
"Cannot convert byte[] to String using UTF-8");
}
}

please image that what happend when b==null!!

**Comment by agazso** [comment]
Fixed in
https://github.com/scalien/scaliendb/commit/ae47ecfb1788d5a357d4829a58ed6b87b42652fc
