### ISSUE TITLE
Database catchup is slow

### ISSUE THREAD

**Issue by agazso** [scalien/scaliendb#387]
It is CPU limited, maybe there are way too many range checks.

**Comment by mtrencseni** [comment]
I commented out the database SET on the receiving side (in ShardCatchupReader) and it's still slow.

**Comment by mtrencseni** [comment]
If the sending side actually doesn't send the messages, it's fast, so it's not the database iteration on the sending side.

**Comment by mtrencseni** [comment]
I also made a version that still serialized the messages but didn't send them over the network. That version was fast.

**Comment by mtrencseni** [comment]
The conclusion of all this is:
- it's not the database on either side
- it's not the Writef() code

It's most likely a networking issue or something on the read size.

**Comment by mtrencseni** [comment]
Speed is 4MB/s (slow) for kvs of size 100 bytes, but 20MB/s for kvs of size 10,000 bytes.

This are the same speeds the client experiences with these kv sizes.

**Comment by mtrencseni** [comment]
Disabled CatchupMessage::Read() on the receiving side, but it's still slow at 4MB/s.

**Comment by mtrencseni** [comment]
I tried to uncomment the YIELD code in MessageConnection::OnRead(), didn't help.

**Comment by mtrencseni** [comment]
I commented out the Log_Trace()s in MessageConnection::OnRead(), didn't help.

**Comment by agazso** [comment]
It was mainly slow on Windows. By fixing buffering issues, it is no longer slow.
