### ISSUE TITLE
Assertions are triggered when disk space runs out

### ISSUE THREAD

**Issue by scalien** [scalien/scaliendb#72]
ScalienDB: src/Framework/Storage/StorageLogSegment.cpp:107: int32_t StorageLogSegment::AppendSet(uint16_t, uint64_t, ReadBuffer&, ReadBuffer&): Assertion `fd != -1' failed.
Aborted

or

ScalienDB: src/Framework/Storage/StorageEnvironment.cpp:1400: void StorageEnvironment::OnChunkMerge(): Assertion `mergeChunkOut->written' failed.
Aborted

**Comment by mtrencseni** [comment]
Stop DB if disk space runs out.

**Comment by scalien** [comment]
See #323
