### ISSUE TITLE
Midpoint calculation is wrong when chunk is splitted or data was inserted in-order

### ISSUE THREAD

**Issue by agazso** [scalien/scaliendb#76]

**Comment by agazso** [comment]
It is half-done, when chunk is splitted it is already fixed.

**Comment by mtrencseni** [comment]
Fixed in

https://github.com/scalien/scaliendb/commit/be9bf072e965ec3922da4f4751ed0881f76f0643

and

https://github.com/scalien/scaliendb/commit/b35d58223478ed0bf11969c967a1c4e150b9d3ca
